### ISSUE TITLE
Where can I download the GEOS-Chem output files?

### ISSUE THREAD

**Issue by Airwhf** [barronh/geos2cmaq#3]
Hi Barron,

I can not find the download links for the GEOS-Chem output files.

And, could you provide me for the code updates to output the chemical species from GEOS-Chem. 

My Email address is: wanghf58@mail2.sysu.edu.cn

Best regards,
Haofan

**Comment by barronh** [comment]
Haofan,

These files are no longer available via UF servers. I will contact you via email to discuss further.
